apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: sample-app-keda
spec:
  scaleTargetRef:
    name: sample-app
  minReplicaCount: 1
  maxReplicaCount: 5
  triggers:
  - type: cpu
    metricType: Utilization
    metadata:
      value: "25"